# Generated by Django 6.0.2 on 2026-02-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe__ingredients_hash_recipe_calories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.CharField(blank=True, help_text='e.g., 2 lbs, 1 gallon', max_length=100)),
                ('storage', models.CharField(choices=[('fridge', 'Refrigerator'), ('freezer', 'Freezer'), ('pantry', 'Pantry')], default='fridge', max_length=10)),
                ('sell_by_date', models.DateField(help_text='Sell-by or use-by date from the package')),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sell_by_date'],
            },
        ),
    ]
