# Generated by Django 6.0.2 on 2026-02-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.CharField(blank=True, help_text='e.g., 2 lbs, 1 dozen', max_length=100)),
                ('section', models.CharField(choices=[('produce', 'Produce'), ('dairy', 'Dairy'), ('meat', 'Meat & Seafood'), ('bakery', 'Bakery'), ('frozen', 'Frozen'), ('pantry', 'Pantry'), ('beverages', 'Beverages'), ('other', 'Other')], default='other', max_length=10)),
                ('checked', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['checked', 'section', 'name'],
            },
        ),
    ]
