# Generated by Django 6.0.2 on 2026-02-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_shoppingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='quantity_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Numeric quantity for tracking (e.g., 5)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='unit',
            field=models.CharField(blank=True, help_text='Unit of measure (e.g., lbs, oz, cups)', max_length=50),
        ),
    ]
