# Generated by Django 6.0.2 on 2026-02-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_pantryitem_quantity_amount_pantryitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='low_stock_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alert when quantity drops to this level (default: 25% of initial quantity)', max_digits=8, null=True),
        ),
    ]
